name: Python Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout your repo
      - uses: actions/checkout@v3

      # 2. Setup Python 3.10
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10

      # 3. Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest inflect

      # 4. Run all tests
      - name: Run pytest
        run: |
          python -m pytest -v
