name: CS50 Python Tests

# Run on push or pull request to main branch
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repo
        uses: actions/checkout@v3

      # Step 2: Set up Python 3.10
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10

      # Step 3: Upgrade pip and install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest inflect

      # Step 4: Run all tests
      - name: Run pytest
        run: python -m pytest -v
